services:
  staff-postgres:
    image: postgres:latest
    container_name: staff-postgres
    environment:
      POSTGRES_DB: staff
      POSTGRES_USER: staff
      POSTGRES_PASSWORD: staff
    ports:
      - "5433:5432"
    volumes:
      - staff_postgres_data:/var/lib/postgresql/data
    networks:
      - kindergarten-net
    restart: unless-stopped

volumes:
  staff_postgres_data:

networks:
  kindergarten-net:
    external: true